### ISSUE TITLE
Use Slither static analyzer to catch smart contract security issues

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/contracts#152]
As we move towards hardening our code, and working with audit firms: the CEO of TrailOfBits was just on Epicenter. Great podcast. [Here it is](https://epicenter.tv/episodes/346/). They've developed [Slither](https://blog.trailofbits.com/2019/05/27/slither-the-leading-static-analyzer-for-smart-contracts/).

Our old smart contracts used TrailOfBits sw, including slither and more. (Details in Ahmed's first Aug 13 comment, below).

The aim of this epic is:
- [x] decide which tools to use: Slither and maybe others (mythril? securify? etc).
- [x] make these tools and other part of our smart contract testing process
- [x] make all our smart contracts pass each tool's testing
