### ISSUE TITLE
Deploy Ocean to Aurora Testnet (NEAR)

### ISSUE THREAD

**Issue by 0x3bfc** [oceanprotocol/contracts#323]
## TODOs
- [ ] Ensure there's a way to get OCEAN bridged over
- [ ] Multisig for OPF Wallet
- [ ] Deploy Ocean Smart Contracts
- [ ] Update ocean.js
- [ ] Deploy provider
- [ ] Add aquarius indexer
- [ ] Update graph
- [ ] Update market
- [ ] Update docs.oceanprotocol.com "supported networks"

## Motivation

Aurora is an Ethereum Virtual Machine created by the stellar team at the NEAR Protocol, delivering a turn-key solution for developers to operate their apps on an Ethereum-compatible, high-throughput, scalable and future-safe platform, with low transaction costs for their users. For more information, please refer to [Aurora docs](https://doc.aurora.dev/develop/networks)

## Advantages
- **Uses ETH** as a base currency
- Totally **Permissionless Bridge**
- **Bridging ERC20 tokens will come up soon**

![image](https://user-images.githubusercontent.com/5428661/121009765-d6eee600-c794-11eb-99f3-384f952516dd.png)

## Faucet

- You can bridge any amount of [Ropsten ETH](https://faucet.ropsten.be/) to Aurora testnet through [Aurora bridge](https://testnet.aurora.dev/bridge). Just connect your Metamask with Ropsten and then you can bridge your tokens to the same address on Aurora. It takes around 2~4 mins to bridge the tokens as it waits for the transaction finality. Finally check out the The Aurora testnet metamask configuration below (Please make sure to use `ETH` as a **currency symbol**).

![image](https://user-images.githubusercontent.com/5428661/121008630-7c08bf00-c793-11eb-9565-306acdcaab39.png)

- Or you can use the Faucet but still doesn't have lots of liquidity [here](https://faucet.testnet.aurora.dev/)

For more details about bridging ETH check out this [tutorial](https://doc.aurora.dev/learn/connect/metamask).

**Comment by 0x3bfc** [comment]
@trentmc Bridging ERC721 and ERC20 should come within couple of weeks.

**Comment by alexcos20** [comment]
Will resume once v4 is out
