### ISSUE TITLE
"createNftWithErc" and similar labels are nonsensical

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/contracts#485]
**Background / Motivation**

"ERC" refers to one of many possible Ethereum proposals, it could be ERC721 (nft), ERC20 (fungible token), ERC725 (identity/metadata), ERC1155, and literally thousands more.

"ERC" without a number means the whole group of Ethereum proposals.

`ERC721Factory.sol` includes the following functions:
- `createNftWithErc` [link](https://github.com/oceanprotocol/contracts/blob/v4main_postaudit/contracts/ERC721Factory.sol#L607)
- `createNftErcWithPool`
- `createNftErcWithFixedRate`
- `createNftErcWithDispenser`

These labels don't make any sense, because there's no number beside the "erc". I'm marking this as a bug because it is also nonsensical in the DX: developers will have no idea what "Erc" refers to here.

**TODO for this issue:** 

- [ ] fix the labels above by putting a number beside them
- [ ] identify any other places in `contracts` repo that has "erc" without a number, and put a number beside them too
- [ ] after deployment, ensure that ocean.js and ocean.py use the updated names, and that _their_ library method names are appropriate too

Related issues:
- [ocean.py#707](https://github.com/oceanprotocol/ocean.py/issues/707): like this one, but downstream for py
- [ocean.js#1251](https://github.com/oceanprotocol/ocean.js/issues/1251): like this one, but downstream for js
